import { Inter } from "next/font/google";
import "./globals.css";
import { Tabsprovider } from "@/context/TabsContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Anitha Porfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Tabsprovider>
          <div>
              {children}
          </div>
      </Tabsprovider>
      </body>
    </html>
  );
}
